### ISSUE TITLE
Lib repositories not found

### ISSUE THREAD

**Issue by lamphamsy** [scality/eclib#29]
The two lib repositories are not found:

http://lab.jerasure.org/jerasure/gf-complete.git
http://lab.jerasure.org/jerasure/jerasure.git

Could they replaced by the following ones?
https://github.com/ceph/gf-complete.git
https://github.com/ceph/jerasure.git

**Comment by vrancurel** [comment]
Also, the new home for liberasure is here:

https://github.com/openstack/liberasurecode

**Comment by ghost** [comment]
So, in the end, we chose to keep the upstream libraries. That means keeping `lab.jerasure.com` for `jerasure` and `gf-complete`.

`liberasure`was updated by #39, closing.
